# Site settings
title: Blackjack
email: filiptodoric.com
description: > # this means to ignore newlines until "baseurl:"
  This is a fully client-side implementation of the classic
  card game Blackjack.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: filiptodoric
github_username:  filiptodoric

# Build settings
markdown: kramdown
